- name: phyton setup
  ansible.builtin.import_role:
    name: common
    tasks_from: phyton-setup.yaml

- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yam

- name: systemd setup
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup.yaml

- name: start and enable {{ component }}
  ansible.builtin.service:
    name: "{{ component }}"
    enabled: yes
    state: restarted
