#  - name: enable nginx:1.24
#    ansible.builtin.command: dnf module enable nginx:1.24 -y

#  - name: install nginx
#    ansible.builtin.dnf:
#     name: nginx
#     state: present

#  - name: remove default nginx content
#    ansible.builtin.file:
#     path: /usr/share/nginx/html/* 
#     state: absent

#  - name: create nginx default content
#    ansible.builtin.file:
#     path: /usr/share/nginx/html/*
#     state: directory

#  - name: download the nginx code
#    ansible.builtin.get_url:
#     url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
#     dest: /tmp/frontend.zip

#  - name: unarchive the nginx zip file
#    ansible.builtin.unarchive:
#     src: /tmp/frontend.zip
#     dest: /usr/share/nginx/html
#     remote_src: yes

#  - name: copy the nginx conf
#    ansible.builtin.copy:
#     src: nginx.conf
#     dest: /etc/nginx/nginx.conf

#  - name: reload the {{ component }}
#    ansible.builtin.systemd_service:
#     daemon_reload: true

#  - name: start and enable nginx
#    ansible.builtin.service:
#     name: nginx
#     enabled: yes
#     state: restarted

- name: Install nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: Remove default nginx content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Create nginx html directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: Download frontend code
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
    dest: /tmp/frontend.zip

- name: Unarchive frontend code
  ansible.builtin.unarchive:
    src: /tmp/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Copy nginx config
  ansible.builtin.copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Start and enable nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes