- name: enable nginx:1.24
  ansible.builtin.command: dnf module enable nginx:1.24 -y

- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: present

- name: Remove default nginx content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Create nginx html directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: Download frontend code
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
    dest: /tmp/frontend.zip

- name: Unarchive frontend code
  ansible.builtin.unarchive:
    src: /tmp/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Copy nginx config
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx