- name: copy the {{ component }} repo
  ansible.builtin.copy:
    src: rabbitmq.repo
    dest: /etc/yum.repos.d/rabbitmq.repo

- name: install {{ component }}
  ansible.builtin.dnf:
    name: rabbitmq-server
    state: present

- name: start and enable {{ component }}
  ansible.builtin.service:
    name: rabbitmq-server
    state: restarted
    enabled: yes

- name: create{{ component }}user
  community.rabbitmq.rabbitmq_user:
    user: roboshop 
    password: roboshop123
    permissions:
      - vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
    state: present