- name: install maven and mysql
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
  - maven
  - mysql 

  - name: clean the maven package
  ansible.builtin.command: mvn clean package
  args:
   chdir: /app 

- name: rename the file
  ansible.builtin.command: mv target/{{ component }}-1.0.jar {{ component }}.jar 
  args:
   chdir: /app

