- name: disable nodejs current version
  ansible.builtin.command: dnf module disable nodejs -y

- name: enable nodejs 20 version
  ansible.builtin.command: dnf module enable nodejs:20 -y

- name: install nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: present

- name: download the npm dependencies
  community.general.npm:
    path: /app
